   # .streamlit/secrets.toml
   [connections.gsheets_dashboard]
   spreadsheet = "https://docs.google.com/spreadsheets/d/1l4rfoVXf4hEED5JMQRtG6ueQk-Y0g0J2S9e9Tszz148/edit?gid=1098387147#gid=1098387147"

   [connections.gsheets_ip]
   spreadsheet = "https://docs.google.com/spreadsheets/d/1l4rfoVXf4hEED5JMQRtG6ueQk-Y0g0J2S9e9Tszz148/edit?gid=0#gid=0"

   [connections.gsheets_funding]
   spreadsheet = "https://docs.google.com/spreadsheets/d/1l4rfoVXf4hEED5JMQRtG6ueQk-Y0g0J2S9e9Tszz148/edit?gid=153171392#gid=153171392"

   [connections.gsheets_admin]
   spreadsheet = "https://docs.google.com/spreadsheets/d/1l4rfoVXf4hEED5JMQRtG6ueQk-Y0g0J2S9e9Tszz148/edit?gid=1726492923#gid=1726492923"

   [connections.gsheets_berkeley]
   spreadsheet = "https://docs.google.com/spreadsheets/d/1l4rfoVXf4hEED5JMQRtG6ueQk-Y0g0J2S9e9Tszz148/edit?gid=1888221568#gid=1888221568"

   [connections.gsheets_ebi2]
   spreadsheet = "https://docs.google.com/spreadsheets/d/1l4rfoVXf4hEED5JMQRtG6ueQk-Y0g0J2S9e9Tszz148/edit?gid=1029064839#gid=1029064839"
   
